local ls = require("luasnip")
local s = ls.snippet
local t = ls.text_node
local i = ls.insert_node
local c = require("snippets.utils").copy

return {

	s("cls", {
		t("class "),
		i(1, "ClassName"),
		t({ ":", "", "    def __init__(self, " }),
		i(2, "arg"),
		t(": "),
		i(3, "type"),
		t({ ") -> None:", "        " }),
		i(4, "pass"),
		i(0),
	}),

	s("clsd", {
		t("class "),
		i(1, "ClassName"),
		t({ ":", '    """', "    " }),
		i(2, "Docstring"),
		t({ "", '    """', "", "    def __init__(self, " }),
		i(2, "arg"),
		t(": "),
		i(3, "type"),
		t({ ") -> None:", "        " }),
		i(4, "pass"),
		i(0),
	}),

	s("fun", {
		t("def "),
		i(1, "function"),
		t("("),
		i(2, "arg"),
		t(": "),
		i(3, "type"),
		t(") -> "),
		i(4, "None"),
		t({ ":", "    " }),
		i(5, "pass"),
		i(0),
	}),

	s("fund", {
		t("def "),
		i(1, "function"),
		t("("),
		i(2, "arg"),
		t(": "),
		i(3, "type"),
		t({ ") -> " }),
		i(4, "None"),
		t({ ":", '    """', "    " }),
		i(5, "Function description"),
		t({ "", "", "    Parameters", "    ----------", "    " }),
		c(2),
		t(" : "),
		c(3),
		t({ "", "        " }),
		i(6, "explanation"),
		t({ "", "", "    Returns", "    -------", "    " }),
		c(4),
		t({ "", "        " }),
		i(7, "explanation"),
		t({ "", '    """', "    " }),
		i(8, "pass"),
		i(0),
	}),

	s("met", {
		t("def "),
		i(1, "method"),
		t("(self, "),
		i(2, "arg"),
		t(": "),
		i(3, "type"),
		t(") -> "),
		i(4, "None"),
		t({ ":", "    " }),
		i(5, "pass"),
		i(0),
	}),

	s("metd", {
		t("def "),
		i(1, "method"),
		t("(self, "),
		i(2, "arg"),
		t(": "),
		i(3, "type"),
		t({ ") -> " }),
		i(4, "None"),
		t({ ":", '    """', "    " }),
		i(5, "Method description"),
		t({ "", "", "    Parameters", "    ----------", "    " }),
		c(2),
		t(" : "),
		c(3),
		t({ "", "        " }),
		i(6, "explanation"),
		t({ "", "", "    Returns", "    -------", "    " }),
		c(4),
		t({ "", "        " }),
		i(7, "explanation"),
		t({ "", '    """', "    " }),
		i(8, "pass"),
		i(0),
	}),

	s("enum", {
		t("for key, value in enumerate("),
		i(1, "iterable"),
		t({ "):", "    " }),
		i(2, "pass"),
		i(0),
	}),

	s("try", {
		t({ "try:", "    " }),
		i(1, "pass"),
		t({ "", "except " }),
		i(2, "Exception"),
		t({ " as " }),
		i(3, "e"),
		t({ ":", "    " }),
		i(4, "pass"),
		i(0),
	}),

	s("with", {
		t('with open("'),
		i(1, "file.txt"),
		t('", "'),
		i(2, "r"),
		t('", '),
		i(3, 'encoding="utf-8"'),
		t({ ") as file:", "    lines = file." }),
		i(4, "readlines"),
		t("()"),
		i(0),
	}),

	s("lam", {
		t("(lambda "),
		i(1, "x"),
		t(": "),
		i(2, "x**2"),
		t(")("),
		c(1),
		t(")"),
		i(0),
	}),

	s("ls", {
		t("["),
		i(1, "item"),
		t(" for "),
		c(1),
		t(" in "),
		i(2, "iterable"),
		t("]"),
		i(0),
	}),

	s("dc", {
		t("{"),
		i(1, "key"),
		t(": "),
		i(2, "value"),
		t(" for "),
		c(1),
		t(", "),
		c(2),
		t(" in "),
		i(3, "iterable"),
		t("}"),
		i(0),
	}),

	s("f", {
		t('f"'),
		i(1, "text"),
		t(" {"),
		i(2, "var"),
		t('}"'),
		i(0),
	}),

	s("pr", {
		t("print("),
		i(1, "var"),
		t(")"),
		i(0),
	}),

	s("prf", {
		t('print(f"'),
		i(1, "text"),
		t(" {"),
		i(2, "var"),
		t('}")'),
		i(0),
	}),

	s("run", {
		t({ 'if __name__ == "__main__":', "    " }),
		i(1, "pass"),
		i(0),
	}),

	s("fr", {
		t("from "),
		i(1, "package"),
		t(" import "),
		i(2, "module"),
		i(0),
	}),

	s("fa", {
		t("from "),
		i(1, "package"),
		t(" import "),
		i(2, "module"),
		t(" as "),
		i(3, "mdl"),
		i(0),
	}),
}
