#################
### AUTOSTART ###
#################

# Startup Services/Widgets
exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
exec-once = /usr/bin/gnome-keyring-daemon --start --components=pkcs11,secrets,ssh
exec-once = dbus-update-activation-environment --systemd DISPLAY WAYLAND_DISPLAY XDG_CURRENT_DESKTOP XAUTHORITY DBUS_SESSION_BUS_ADDRESS
exec-once = systemctl --user import-environment DISPLAY WAYLAND_DISPLAY XDG_CURRENT_DESKTOP XAUTHORITY DBUS_SESSION_BUS_ADDRESS

# Required by GNOME apps such as GNOME-Music
exec-once = systemctl --user start localsearch-3.service

exec-once = qs -c noctalia-shell
exec-once = qs -c overview
exec-once = hypridle
exec-once = swww-daemon
exec-once = niri-screen-time -daemon 

exec-once = wl-paste --type text --watch cliphist store &
exec-once = wl-paste --type image --watch cliphist store &

exec-once = hyprctl setcursor volantes_cursors 24

# exec-once = hyprpm reload

# Startup Apps
exec-once = arch-update --tray
exec-once = sleep 1 && discord
exec-once = sleep 1 && easyeffects --gapplication-service
exec-once = sleep 1 && spotify
exec-once = steam
exec-once = ghostty --class="btm-monitor" --title="btm-monitor" -e btm
