$terminal     = ghostty
$termexec     = ghostty -e
$fileManager  = nautilus
$browser      = brave
$editor       = ghostty -e nvim
$music        = spotify
$calculator   = gnome-calculator
$currencyConv = valuta
$musicPlayer  = amberol
$imageViewer  = loupe
$videoPlayer  = showtime
$resourceMon  = resources
