########################
### STEAM GAME RULES ###
########################

# General Game
windowrule {
    name = steam-game
    match:class = steam_app.*
    fullscreen = true
    workspace = 1
    focus_on_activate = true
    tag = game
}

##################################

windowrule {
    name = squad-launcher
    match:class = steam_app_393380
    match:title = SquadGame
    float = true
    fullscreen = false
    workspace = 1 silent
    focus_on_activate = false
}

windowrule {
    name = squad-launcher-2
    match:class = steam_app_393380
    match:title = ^$
    float = true
    fullscreen = false
    workspace = 1 silent
    focus_on_activate = false
}

##################################

windowrule {
    name = megabonk
    match:class = Megabonk\.x86_64
    fullscreen = true
    workspace = 1
    focus_on_activate = true
    tag = game
}

##################################

windowrule {
    name = slay-the-spire
    match:class = Slay the Spire|Slay the Spire 2
    fullscreen = true
    workspace = 1
    focus_on_activate = true
    tag = game
}

##################################

windowrule {
    name = beamng
    match:class = BeamNG\.drive\.x64
    fullscreen = true
    workspace = 1
    focus_on_activate = true
    tag = game
}

##################################

windowrule {
    name = seven-days-to-end-with-you
    match:class = steam_app_1859280
    match:title = Seven Days to End with You
    fullscreen = false
    workspace = 1
    focus_on_activate = true
    float = true
    center = true
    size = 1600 900
    tag = game
}

##################################

windowrule {
    name = lari-launcher
    match:class = steam_app_1086940
    match:title = LariLauncher
    fullscreen = false
    workspace = 1 silent
    focus_on_activate = false
    float = true
    center = true
}

windowrule {
    name = baldurs-gate-3
    match:class = bg3
    match:title = Baldur's Gate 3.*
    fullscreen = true
    workspace = 1
    focus_on_activate = true
    tag = game
}

##################################

windowrule {
    name = ready-or-not-launcher
    match:class = steam_app_1144200
    fullscreen = false
    float = true
    center = true
    workspace = 1 silent
    focus_on_activate = true
}
