########################
### STEAM GAME RULES ###
########################

# General Game
windowrule {
    name = steam-game
    match:class = steam_app.*
    float = false
    fullscreen = true
    workspace = 1
}

##################################

windowrule {
    name = squad-launcher
    match:class = steam_app_393380
    match:title = SquadGame
    float = true
    fullscreen = false
    workspace = 1
}

windowrule {
    name = squad-launcher-2
    match:class = steam_app_393380
    match:title = ^$
    float = true
    fullscreen = false
    workspace = 1
}

##################################

windowrule {
    name = megabonk
    match:class = Megabonk\.x86_64
    float = false
    fullscreen = true
    workspace = 1
}

##################################

windowrule {
    name = slay-the-spire
    match:class = Slay the Spire
    float = false
    fullscreen = true
    workspace = 1
}

##################################

windowrule {
    name = beamng
    match:class = BeamNG\.drive\.x64
    float = false
    fullscreen = true
    workspace = 1
}

##################################

windowrule {
    name = slay-the-spire-2
    match:class = Slay the Spire 2
    fullscreen = true
    workspace = 1
}

##################################

windowrule {
    name = seven-days-to-end-with-you
    match:class = steam_app_1859280
    match:title = Seven Days to End with You
    fullscreen = false
    float = true
    center = true
    size = 1600 900
}
